/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cafedose;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
/**
 *
 * @author kim
 */

public class login extends javax.swing.JFrame {
    HashMap<String, String> accounts = new HashMap<>();
    
    private String textfield="";
    private String pwfield="●●●●●●●●●●";
    
 private boolean checkLogin(String file, String user, String pass) {
    try (BufferedReader br = new BufferedReader(new FileReader(file))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] credentials = line.split(",");
            if (credentials[0].equals(user) && credentials[1].equals(pass)) {
                return true;
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
    return false;
}
   private void handleError() {
    if(attempt >= 5) {
        new error().setVisible(true);
    } else {
        JOptionPane.showMessageDialog(rootPane,"Invalid Email or Password");
        jTextField1.setText("");   
        jPasswordField1.setText("");
        attempt++;            
    }
}
    int attempt=0;
    LocalTime currentTime = LocalTime.now();
    
    
    int hour,min,sec;
    String timestr;
    
private boolean showPassword = false;
    /**
     * Creates new form login
     */
    public String getTimeNow() {
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MMM dd, yyyy hh:mm:ss a");
    return sdf.format(new java.util.Date());
    }
    
    public login() {
        initComponents();
        
         LocalTime currentTime = LocalTime.now();
        jTextField1.setText(textfield);
        jTextField1.setForeground(Color.blue);
        jPasswordField1.setText(pwfield);
        
                      
  

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setForeground(new java.awt.Color(0, 51, 102));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 180, -1));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 180, 20));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 180, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 80, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("forget password?");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/portal.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String user = jTextField1.getText().trim();
    String pass = new String(jPasswordField1.getPassword()).trim();
    
    // Clear password immediately
    jPasswordField1.setText("");
    
    
    
    if (datalog.accounts.containsKey(user) && datalog.accounts.get(user).equals(pass)) {
        // ✅ SUCCESS
        attempt = 0;
        String time = getTimeNow();
        datalog.addLog(user, time, "", "SUCCESS");
        datalog.currentUser = user;
        datalog.currentLogIndex = datalog.logs.size() - 1;
        
        if(user.equals("AD123")) {
            JOptionPane.showMessageDialog(rootPane, "Welcome, DAVI");
        } else if(user.equals("CS456")) {
            JOptionPane.showMessageDialog(rootPane, "Welcome, JUNEY");
        } else if(user.equals("CS789")) {
            JOptionPane.showMessageDialog(rootPane, "Welcome, BRLLY");
        }
        
        this.dispose();
        new loading().setVisible(true);
        
    } else {
        // ✅ FAILED
        String time = getTimeNow();
       datalog.addLog(user, time, "", "FAILED");
        
        if(attempt >= 5) {
            new error().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, 
                String.format("Invalid Credentials\nAttempts: %d/5", attempt + 1));
            jTextField1.setText("");   
            jPasswordField1.setText("");
            attempt++;
        }
    }

    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Object[] options = {"No", "Yes"};
        int userChoice = JOptionPane.showOptionDialog(rootPane, "Are you sure you want close?", "Leave",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, options,
                options[0]);
        if (userChoice == 0) {
           
        }else if (userChoice == 1) {
        
            System.exit(0);}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       String user = JOptionPane.showInputDialog(this, "Enter your ID:");
if(user == null) return;

String cleanUser = user.trim();
if(cleanUser.isEmpty()) {
    JOptionPane.showMessageDialog(this, "ID cannot be empty!");
    return;
}

if(datalog.accounts.containsKey(cleanUser)) {
    String newPass = JOptionPane.showInputDialog(this, "Enter new password:");
    if(newPass == null || newPass.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Password cannot be empty!");
        return;
    }
    String time = getTimeNow();
        datalog.addLog(user + "Password:"+ newPass, time, "", "CHANGED");
    datalog.accounts.put(cleanUser, newPass.trim());
    JOptionPane.showMessageDialog(this, "Password successfully updated!");
} else {
    JOptionPane.showMessageDialog(this, "ID not found!");
}                                       
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private static class accounts {

        private static boolean containsKey(String user) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static Object get(String user) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static void put(String user, String newPass) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public accounts() {
        }
    }

    private static class admin {

        public admin() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }

}

