/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cafedose;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author monio
 */
public class adm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adm.class.getName());

    /**
     * Creates new form adm
     */
    public adm() {
        initComponents();
        loadTable();
        loadLogTable();
        time.setVisible(false);
        report.setVisible(false);
        stock.setVisible(false);
    }
    public String getTimeNow() {
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("hh:mm:ss a");
    return sdf.format(new java.util.Date());
    }
    public void loadLogTable() {
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    model.setRowCount(0); // clear existing rows

    for(log l : datastore.log) {
        model.addRow(new Object[]{
            l.cashier,
            l.item,
            l.quantity,
            l.amount,
            l.timeIn
        });
    }
}
public void loadTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    for (String[] row : datalog.logs) {
        model.addRow(row);
    }
}
    public String TIMEOUT() {
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("hh:mm:ss a");
    return sdf.format(new java.util.Date());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        time = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        report = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        stock = new javax.swing.JPanel();
        jTextFieldStock = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelStocks = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(163, 195, 233));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton49.setBackground(new java.awt.Color(153, 204, 255));
        jButton49.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jButton49.setText("REPORT");
        jButton49.setBorder(javax.swing.BorderFactory.createBevelBorder(null));
        jButton49.addActionListener(this::jButton49ActionPerformed);
        jPanel2.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 130, 50));

        jButton50.setBackground(new java.awt.Color(153, 204, 255));
        jButton50.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jButton50.setText("TOR");
        jButton50.setBorder(javax.swing.BorderFactory.createBevelBorder(null));
        jButton50.addActionListener(this::jButton50ActionPerformed);
        jPanel2.add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 150, 50));

        jButton51.setBackground(new java.awt.Color(153, 204, 255));
        jButton51.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jButton51.setText("STOCK");
        jButton51.setBorder(javax.swing.BorderFactory.createBevelBorder(null));
        jButton51.addActionListener(this::jButton51ActionPerformed);
        jPanel2.add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 150, 50));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logohex.png"))); // NOI18N
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 120, 110));

        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("ADMIN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 120, -1));

        jButton3.setBackground(new java.awt.Color(102, 153, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jButton3.setText("LOGOUT");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 150, -1));

        jButton4.setBackground(new java.awt.Color(204, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton4.setText("<>");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 60, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 500));

        time.setBackground(new java.awt.Color(0, 0, 102));
        time.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "EMAIL", "TIME IN", "TIME OUT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        time.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 530, 490));

        report.setBackground(new java.awt.Color(0, 51, 153));
        report.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cashier", "Item", "Quantity", "Amount", "Time"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        report.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 510, 470));

        jPanel1.add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 550, 510));

        stock.setBackground(new java.awt.Color(102, 153, 255));
        stock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        stock.add(jTextFieldStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 80, -1));

        jButton1.setText("update");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        stock.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabelStocks.setText("...");
        stock.add(jLabelStocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 80, 20));

        jPanel1.add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 570, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        // TODO add your handling code here:
        loadLogTable();
       report.setVisible(true);
       time.setVisible(false);
       stock.setVisible(false);
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        // TODO add your handling code here:
        time.setVisible(true);
         report.setVisible(false);
         stock.setVisible(false);
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // TODO add your handling code here:
        stock.setVisible(true);
        time.setVisible(false);
         report.setVisible(false);
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Object[] options = {"No", "Yes"};
        int userChoice = JOptionPane.showOptionDialog(rootPane, "Are you sure you want close?", "Leave",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null, options,
            options[0]);
        if (userChoice == 0) {

        }else if (userChoice == 1) {

            this.setVisible(false);
            new loadingS().setVisible(true);}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int choice = JOptionPane.showConfirmDialog(null,
                "Are sure you want to log out?",
                "Log Out",
                JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
           
            // BABAGUHIN
           String username = datalog.currentUser;
    String timeOut = getTimeNow();

    // CODE KO SA SAME ROW
    for (int i = datalog.logs.size() - 1; i >= 0; i--) {
        String[] row = datalog.logs.get(i);

        if (row[0].equals(username)
                && row[1] != null && !row[1].isEmpty()
                && (row[2] == null || row[2].isEmpty())) {

            row[2] = timeOut; // PARA SAME ROW
            break;
        }
    }
         this.setVisible(false);
            new login().setVisible(true);
        } else if (choice == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null, "Log Out Cancelled");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        loadLogTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int newStock = Integer.parseInt(jTextFieldStock.getText().trim());

            if (newStock < 0) {
                JOptionPane.showMessageDialog(null, "Stock cannot be negative!");
                return;
            }

            Stock.coffeeStock = newStock;
            jLabelStocks.setText("Stock: " + Stock.coffeeStock);

            // Optional: update Sales UI
            // salesForm.refreshSpinner();

            JOptionPane.showMessageDialog(null, "Stock Updated!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Enter valid number!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelStocks;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldStock;
    private javax.swing.JPanel report;
    private javax.swing.JPanel stock;
    private javax.swing.JPanel time;
    // End of variables declaration//GEN-END:variables
}
